[package]
name = "find-id-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui_extras = "0.32.0"
env_logger = "0.11.8"
glob = "0.3.2"
rayon = "1.10.0"
rfd = "0.15.4"
roxmltree = "0.20.0"
tokio = { version = "1", features = ["full"] }
